function createfigure(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  stairs x
%  Y1:  stairs y

%  Auto-generated by MATLAB on 08-Feb-2018 09:19:38

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create stairs
stairs(X1,Y1,'DisplayName','šinusoida','Color',[0 0 0]);

% Create xlabel
xlabel('t,s');

% Create title
title('Mans pirmais grafiks');

% Create ylabel
ylabel('U,V');

box(axes1,'on');
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'Color',[0 0.498039215803146 0],'XAxisLocation','top','XColor',...
    [0.850980401039124 0.325490206480026 0.0980392172932625],'XMinorTick','on',...
    'XScale','log','YColor',...
    [0.850980401039124 0.325490206480026 0.0980392172932625],'ZColor',...
    [0.850980401039124 0.325490206480026 0.0980392172932625]);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Color',[1 1 1]);

