#!/usr/bin/python
# -*- coding: utf-8 -*-
# 4. piemers

print "Here \nthe \nspaces \nare \nnewlined."

'''
'''
# 3.piemers

print "Here \bthe \bspaces \bare \bbackspaced."

'''
# 1. piemers

print "Hello World!"
'''




 
